openapi: 3.0.0
info:
  title: Webservice ArzTI API
  description: "Kommunikation des Webservers mit den jeweiligen Rechenzentren
  
  * UC: Abruf der eRezept-Daten - neue (noch nicht gesendete) | eRezept-ID | Zeitraum
  
  * UC: Abruf der eMuster16-Daten - neue (noch nicht gesendete) | eRezept-ID | Zeitraum
  
  * UC: Abruf der pRezept-Daten - neue (noch nicht gesendete) | eRezept-ID | Zeitraum
  
  * UC: Aktualisierung des eRezept-Status - eRezept-ID
  
  * UC: Löschen eines eRezepts - eRezept-ID
  
  * UC: Aktualisierung von Kundendaten (Apotheke -> Rechenzentrum Zuordnung) - Apotheke-IK
  
  * UC: ...
"
  version: V1
servers:
  - url: http://arzsoftware.de/v1
    description: Main (production) server
  - url: http://staging-api.arzsoftware.de
    description: Internal staging server for testing
paths:
# M-Rezeptre
  /apotheke/{apoik}/mrezept:
    get:
      tags:
        - M-Rezept
      summary: liefert eine Liste von M-Rezepten
      description: ""
      security:
        - BasicAuth: [arz_read]
  /apotheke/{apoik}/mrezept/status:
    get:
      tags:
        - M-Rezept
      summary: Statusabfrage aller M-Rezepte
      description: ""
      security:
        - BasicAuth: [arz_read]
  /apotheke/{apoik}/mrezept/{rezid}:
    get:
      tags:
        - M-Rezept
      summary: liefert ein M-Rezept
      description: ""
      security:
        - BasicAuth: [arz_read]
    delete:
      tags:
        - M-Rezept
      summary: löscht ein M-Rezept
      description: ""
      security:
        - BasicAuth: [arz_write]
  /apotheke/{apoik}/mrezept/{rezid}/Abholstatus:
    put:
      tags:
        - M-Rezept
      summary: Änderung des M-Rezept Abholstatus
      description: "ändert Abholstatus einer Liste von M-Rezepten"
      operationId: "aendereAbholstatusRezeptList"
      security:
        - BasicAuth: [arz_read]
  /apotheke/{apoik}/mrezept/{rezid}/pruefung:
    put:
      tags:
        - M-Rezept
      summary: prüft ein M-Rezept
      description: ""
      security:
        - BasicAuth: [arz_read]
  /apotheke/{apoik}/mrezept/{rezid}/status:
    get:
      tags:
        - M-Rezept
      summary: Statusabfrage des M-Rezeptes
      description: ""
      security:
        - BasicAuth: [arz_read]
    patch:
      tags:
        - M-Rezept
      summary: Statusänderung des M-Rezeptes
      description: ""
      security:
        - BasicAuth: [arz_read]
# P-Rezepte
  /apotheke/{apoik}/prezept:
    get:
      tags:
        - P-Rezept
      summary: liefert eine Liste von P-Rezepten
      description: ""
      security:
        - BasicAuth: [arz_read]
  /apotheke/{apoik}/prezept/status:
    get:
      tags:
        - P-Rezept
      summary: Statusabfrage aller P-Rezepte
      description: ""
      security:
        - BasicAuth: [arz_read]
  /apotheke/{apoik}/prezept/{rezid}:
    get:
      tags:
        - P-Rezept
      summary: liefert ein P-Rezept
      description: ""
      security:
        - BasicAuth: [arz_read]
    delete:
      tags:
        - P-Rezept
      summary: löscht ein P-Rezept
      description: ""
      security:
        - BasicAuth: [arz_write]
  /apotheke/{apoik}/prezept/{rezid}/Abholstatus:
    put:
      tags:
        - P-Rezept
      summary: Änderung des P-Rezept Abholstatus
      description: "ändert Abholstatus einer Liste von P-Rezepten"
      operationId: "aendereAbholstatusRezeptList"
      security:
        - BasicAuth: [arz_read]
  /apotheke/{apoik}/prezept/{rezid}/pruefung:
    put:
      tags:
        - P-Rezept
      summary: prüft ein P-Rezept
      description: ""
      security:
        - BasicAuth: [arz_read]
  /apotheke/{apoik}/prezept/{rezid}/status:
    get:
      tags:
        - P-Rezept
      summary: Statusabfrage des P-Rezeptes
      description: ""
      security:
        - BasicAuth: [arz_read]
    patch:
      tags:
        - P-Rezept
      summary: Statusänderung des P-Rezeptes
      description: ""
      security:
        - BasicAuth: [arz_read]
# E-Rezepte
  /apotheke/{apoik}/erezept:
    get:
      tags:
        - E-Rezept
      summary: liefert eine Liste von E-Rezepten
      description: ""
      security:
        - BasicAuth: [arz_read]
  /apotheke/{apoik}/erezept/status:
    get:
      tags:
        - E-Rezept
      summary: Statusabfrage aller E-Rezepte
      description: ""
      security:
        - BasicAuth: [arz_read]
  /apotheke/{apoik}/erezept/{rezid}:
    get:
      tags:
        - E-Rezept
      summary: liefert ein E-Rezept
      description: ""
      security:
        - BasicAuth: [arz_read]
    delete:
      tags:
        - E-Rezept
      summary: löscht ein E-Rezept
      description: ""
      security:
        - BasicAuth: [arz_write]
  /apotheke/{apoik}/erezept/{rezid}/Abholstatus:
    put:
      tags:
        - E-Rezept
      summary: Änderung des E-Rezept Abholstatus
      description: "ändert Abholstatus einer Liste von E-Rezepten"
      operationId: "aendereAbholstatusERezeptList"
      security:
        - BasicAuth: [arz_read]
  /apotheke/{apoik}/erezept/{rezid}/pruefung:
    put:
      tags:
        - E-Rezept
      summary: prüft ein E-Rezept
      description: ""
      security:
        - BasicAuth: [arz_read]
  /apotheke/{apoik}/erezept/{rezid}/status:
    get:
      tags:
        - E-Rezept
      summary: Statusabfrage des E-Rezeptes
      description: ""
      security:
        - BasicAuth: [arz_read]
    patch:
      tags:
        - E-Rezept
      summary: Statusänderung des E-Rezeptes
      description: ""
      security:
        - BasicAuth: [arz_read]
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

tags:
  - name: M-Rezept
    description: Alle Operationen für ein Muster16 Rezept                
  - name: P-Rezept
    description: Alle Operationen für ein Parantelia Rezept         
  - name: E-Rezept
    description: Alle Operationen für ein E Rezept             