/*
 * Webservice ArzTI API
 *
 * Kommunikation des Webservers mit den jeweiligen Rechenzentren V.2021-05-20 
 *
 * The version of the OpenAPI document: V1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using ArzTiClient.Client;
using ArzTiClient.Api;
using ArzTiClient.Model;

namespace ArzTiClient.Test
{
    /// <summary>
    ///  Class for testing RezeptUIDListApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class RezeptUIDListApiTests
    {
        private RezeptUIDListApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new RezeptUIDListApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RezeptUIDListApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' RezeptUIDListApi
            //Assert.IsInstanceOf(typeof(RezeptUIDListApi), instance);
        }

        
        /// <summary>
        /// Test PatchRezeptUIdListAbholstatus
        /// </summary>
        [Test]
        public void PatchRezeptUIdListAbholstatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<RezeptUId> rezeptUId = null;
            //var response = instance.PatchRezeptUIdListAbholstatus(rezeptUId);
            //Assert.IsInstanceOf(typeof(List<Abholstatus>), response, "response is List<Abholstatus>");
        }
        
        /// <summary>
        /// Test PatchRezeptUIdListStatus
        /// </summary>
        [Test]
        public void PatchRezeptUIdListStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<RezeptStatus> rezeptStatus = null;
            //var response = instance.PatchRezeptUIdListStatus(rezeptStatus);
            //Assert.IsInstanceOf(typeof(List<RezeptStatus>), response, "response is List<RezeptStatus>");
        }
        
        /// <summary>
        /// Test PutRezeptUidListPruefung
        /// </summary>
        [Test]
        public void PutRezeptUidListPruefungTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<RezeptUId> rezeptUId = null;
            //instance.PutRezeptUidListPruefung(rezeptUId);
            
        }
        
    }

}
