/*
 * Webservice ArzTI API
 *
 * Kommunikation des Webservers mit den jeweiligen Rechenzentren V.2021-05-20 
 *
 * The version of the OpenAPI document: V1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using ArzTiClient.Client;
using ArzTiClient.Api;
using ArzTiClient.Model;

namespace ArzTiClient.Test
{
    /// <summary>
    ///  Class for testing RezeptIDApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class RezeptIDApiTests
    {
        private RezeptIDApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new RezeptIDApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RezeptIDApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' RezeptIDApi
            //Assert.IsInstanceOf(typeof(RezeptIDApi), instance);
        }

        
        /// <summary>
        /// Test DeleteRezeptId
        /// </summary>
        [Test]
        public void DeleteRezeptIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string apoik = null;
            //RezeptTyp reztyp = null;
            //string rezid = null;
            //var response = instance.DeleteRezeptId(apoik, reztyp, rezid);
            //Assert.IsInstanceOf(typeof(Rezept), response, "response is Rezept");
        }
        
        /// <summary>
        /// Test GetRezeptId
        /// </summary>
        [Test]
        public void GetRezeptIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string apoik = null;
            //RezeptTyp reztyp = null;
            //string rezid = null;
            //var response = instance.GetRezeptId(apoik, reztyp, rezid);
            //Assert.IsInstanceOf(typeof(Rezept), response, "response is Rezept");
        }
        
        /// <summary>
        /// Test GetRezeptIdStatus
        /// </summary>
        [Test]
        public void GetRezeptIdStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string apoik = null;
            //RezeptTyp reztyp = null;
            //string rezid = null;
            //var response = instance.GetRezeptIdStatus(apoik, reztyp, rezid);
            //Assert.IsInstanceOf(typeof(Rezept), response, "response is Rezept");
        }
        
        /// <summary>
        /// Test PatchRezeptIdStatus
        /// </summary>
        [Test]
        public void PatchRezeptIdStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string apoik = null;
            //RezeptTyp reztyp = null;
            //string rezid = null;
            //string status = null;
            //var response = instance.PatchRezeptIdStatus(apoik, reztyp, rezid, status);
            //Assert.IsInstanceOf(typeof(RezeptStatus), response, "response is RezeptStatus");
        }
        
    }

}
