{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "Webservice ArzTI API",
    "description" : "Kommunikation des Webservers mit den jeweiligen Rechenzentren\n* UC: Abruf der eRezept-Daten - neue (noch nicht gesendete) | eRezept-ID | Zeitraum\n* UC: Abruf der eMuster16-Daten - neue (noch nicht gesendete) | eRezept-ID | Zeitraum\n* UC: Abruf der pRezept-Daten - neue (noch nicht gesendete) | eRezept-ID | Zeitraum\n* UC: Aktualisierung des eRezept-Status - eRezept-ID\n* UC: Löschen eines eRezepts - eRezept-ID\n* UC: Aktualisierung von Kundendaten (Apotheke -> Rechenzentru[...]",
    "version" : "V1"
  },
  "servers" : [ {
    "url" : "http://arzsoftware.de/v1",
    "description" : "Main (production) server"
  }, {
    "url" : "http://staging-api.arzsoftware.de",
    "description" : "Internal staging server for testing"
  } ],
  "tags" : [ {
    "name" : "RezeptID",
    "description" : "Alle Operationen für ein Rezept per Rezept-ID"
  }, {
    "name" : "RezeptUID",
    "description" : "Alle Operationen für ein Rezept per Rezept-UID"
  }, {
    "name" : "RezeptIDList",
    "description" : "Alle Operationen für RezeptListen per Rezept-ID"
  }, {
    "name" : "RezeptUIDList",
    "description" : "Alle Operationen für RezeptListen per Rezept-UID"
  } ],
  "paths" : {
    "/apotheke/{apoik}/rezept" : {
      "get" : {
        "tags" : [ "RezeptIDList" ],
        "summary" : "liefert eine Liste von Rezepten  einer Apotheke",
        "description" : "Für die angegebene ApoIK werden alle Rezepte zurückgegeben.\r\n\r\n Optional kann ein Rezepttyp angegeben werden und die maximale Anzahl der Datensätze, die zurückgegeben werden. \r\n\r\n Optional kann ein Zeitraum in der Form yyyy-mm angegeben werden und die maximale Anzahl der Datensätze, die zurückgegeben werden. \r\n\r\n Es werden solange neue Datensätze zurückgegenben, bis keine neuen mehr vorhanden sind.",
        "operationId" : "getRezeptIdList",
        "security" : [ {
          "BasicAuth" : [ "arz_read" ]
        } ]
      }
    },
    "/apotheke/{apoik}/rezept/neu" : {
      "get" : {
        "tags" : [ "RezeptIDList" ],
        "summary" : "Abfrage aller neuen Rezepte einer Apotheke",
        "description" : "Für die angegebene ApoIK werden alle Rezepte zurückgegeben, die noch nicht abgeholt wurden. \r\n\r\n Optional kann ein Zeitraum in der Form yyyy-mm angegeben werden und die maximale Anzahl der Datensätze, die zurückgegeben werden. \r\n\r\n Es werden solange neue Datensätze zurückgegenben, bis keine neuen mehr vorhanden sind.",
        "operationId" : "getRezeptIdListByTransfer",
        "security" : [ {
          "BasicAuth" : [ "arz_read" ]
        } ]
      }
    },
    "/apotheke/{apoik}/rezept/status" : {
      "get" : {
        "tags" : [ "RezeptIDList" ],
        "summary" : "Statusabfrage aller Rezepte einer Apotheke",
        "operationId" : "getRezeptIdListByStatus",
        "security" : [ {
          "BasicAuth" : [ "arz_read" ]
        } ]
      }
    },
    "/apotheke/{apoik}/rezept/abholung" : {
      "put" : {
        "tags" : [ "RezeptIDList" ],
        "summary" : "Änderung des Abholstatus einer Liste von Rezepten",
        "description" : "ändert Abholstatus einer Liste von Rezepten",
        "operationId" : "putRezeptIdListAbholstatus",
        "security" : [ {
          "BasicAuth" : [ "arz_read" ]
        } ]
      }
    },
    "/apotheke/{apoik}/rezept/pruefung" : {
      "put" : {
        "tags" : [ "RezeptIDList" ],
        "summary" : "prüft eine Liste von Rezepten",
        "description" : "Vorprüfung einer Liste von Rezepten",
        "operationId" : "putRezeptIdListPruefung",
        "security" : [ {
          "BasicAuth" : [ "arz_read" ]
        } ]
      }
    },
    "/apotheke/{apoik}/rezept/{reztyp}/{rezid}" : {
      "get" : {
        "tags" : [ "RezeptID" ],
        "summary" : "liefert ein Rezept",
        "operationId" : "getRezeptId",
        "security" : [ {
          "BasicAuth" : [ "arz_read" ]
        } ]
      },
      "delete" : {
        "tags" : [ "RezeptID" ],
        "summary" : "löscht ein Rezept",
        "operationId" : "deleteRezeptId",
        "security" : [ {
          "BasicAuth" : [ "arz_write" ]
        } ]
      },
      "patch" : {
        "tags" : [ "RezeptID" ],
        "summary" : "Statusänderung eines Rezeptes",
        "description" : "Statusänderung eines Rezeptes",
        "operationId" : "patchRezeptIdStatus",
        "security" : [ {
          "BasicAuth" : [ "arz_read" ]
        } ]
      }
    },
    "/apotheke/{apoik}/rezept/{reztyp}/{rezid}/status" : {
      "get" : {
        "tags" : [ "RezeptID" ],
        "summary" : "Statusabfrage eines Rezeptes",
        "description" : "Statusabfrage eines Rezeptes",
        "operationId" : "getRezeptIdStatus",
        "security" : [ {
          "BasicAuth" : [ "arz_read" ]
        } ]
      }
    },
    "/rezept/{ruid}" : {
      "get" : {
        "tags" : [ "RezeptUID" ],
        "summary" : "liefert ein Rezept",
        "operationId" : "getRezeptUId",
        "security" : [ {
          "BasicAuth" : [ "arz_read" ]
        } ]
      },
      "delete" : {
        "tags" : [ "RezeptUID" ],
        "summary" : "löscht ein Rezept",
        "operationId" : "deleteRezeptUId",
        "security" : [ {
          "BasicAuth" : [ "arz_write" ]
        } ]
      },
      "patch" : {
        "tags" : [ "RezeptUID" ],
        "summary" : "Statusänderung eines Rezeptes",
        "description" : "Statusänderung eines Rezeptes",
        "operationId" : "patchRezeptUIdStatus",
        "security" : [ {
          "BasicAuth" : [ "arz_read" ]
        } ]
      }
    },
    "/rezept/abholung" : {
      "put" : {
        "tags" : [ "RezeptUIDList" ],
        "summary" : "Änderung des Abholstatus einer Liste von Rezepten",
        "description" : "ändert Abholstatus einer Liste von Rezepten",
        "operationId" : "putRezeptUIdListAbholstatus",
        "security" : [ {
          "BasicAuth" : [ "arz_read" ]
        } ]
      }
    },
    "/rezept/pruefung" : {
      "put" : {
        "tags" : [ "RezeptUIDList" ],
        "summary" : "prüft eine Liste von Rezepten",
        "description" : "Vorprüfung einer Liste von Rezepten",
        "operationId" : "putRezeptUidListPruefung",
        "security" : [ {
          "BasicAuth" : [ "arz_read" ]
        } ]
      }
    },
    "/apotheke" : {
      "get" : {
        "tags" : [ "Apotheke" ],
        "summary" : "liefert eine Liste aller Apotheken",
        "operationId" : "getApothekenList",
        "security" : [ {
          "BasicAuth" : [ "arz_read" ]
        } ]
      }
    },
    "/apotheke/{apoik}" : {
      "get" : {
        "tags" : [ "Apotheke" ],
        "summary" : "liefert Details einer Apotheke",
        "operationId" : "getApothekeByIK",
        "security" : [ {
          "BasicAuth" : [ "arz_read" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "BasicAuth" : {
        "type" : "http",
        "scheme" : "basic"
      }
    }
  }
}
