/*
 * Webservice ArzTI API
 *
 * Kommunikation des Webservers mit den jeweiligen Rechenzentren V.2021-05-20 
 *
 * The version of the OpenAPI document: V1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ArzTiClient.Client.OpenAPIDateConverter;

namespace ArzTiClient.Model
{
    /// <summary>
    /// E-, M-, oder P-Rezept
    /// </summary>
    /// <value>E-, M-, oder P-Rezept</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum RezeptTyp
    {
        /// <summary>
        /// Enum ERezept for value: ERezept
        /// </summary>
        [EnumMember(Value = "ERezept")]
        ERezept = 1,

        /// <summary>
        /// Enum MRezept for value: MRezept
        /// </summary>
        [EnumMember(Value = "MRezept")]
        MRezept = 2,

        /// <summary>
        /// Enum PRezept for value: PRezept
        /// </summary>
        [EnumMember(Value = "PRezept")]
        PRezept = 3

    }

}
