/*
 * Webservice ArzTI API
 *
 * Kommunikation des Webservers mit den jeweiligen Rechenzentren V.2021-05-20 
 *
 * The version of the OpenAPI document: V1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ArzTiClient.Api;
using ArzTiClient.Model;
using ArzTiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ArzTiClient.Test
{
    /// <summary>
    ///  Class for testing RezeptId
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RezeptIdTests
    {
        // TODO uncomment below to declare an instance variable for RezeptId
        //private RezeptId instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RezeptId
            //instance = new RezeptId();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RezeptId
        /// </summary>
        [Test]
        public void RezeptIdInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" RezeptId
            //Assert.IsInstanceOf(typeof(RezeptId), instance);
        }


        /// <summary>
        /// Test the property 'Typ'
        /// </summary>
        [Test]
        public void TypTest()
        {
            // TODO unit test for the property 'Typ'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

    }

}
