/*
 * Webservice ArzTI API
 *
 * Kommunikation des Webservers mit den jeweiligen Rechenzentren V.2021-05-20 
 *
 * The version of the OpenAPI document: V1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ArzTiClient.Api;
using ArzTiClient.Model;
using ArzTiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ArzTiClient.Test
{
    /// <summary>
    ///  Class for testing RezeptUId
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RezeptUIdTests
    {
        // TODO uncomment below to declare an instance variable for RezeptUId
        //private RezeptUId instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RezeptUId
            //instance = new RezeptUId();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RezeptUId
        /// </summary>
        [Test]
        public void RezeptUIdInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" RezeptUId
            //Assert.IsInstanceOf(typeof(RezeptUId), instance);
        }


        /// <summary>
        /// Test the property 'Ruid'
        /// </summary>
        [Test]
        public void RuidTest()
        {
            // TODO unit test for the property 'Ruid'
        }

    }

}
