/*
 * Webservice ArzTI API
 *
 * Kommunikation des Webservers mit den jeweiligen Rechenzentren V.2021-05-20 
 *
 * The version of the OpenAPI document: V1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ArzTiClient.Api;
using ArzTiClient.Model;
using ArzTiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ArzTiClient.Test
{
    /// <summary>
    ///  Class for testing RezeptPruefResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RezeptPruefResultTests
    {
        // TODO uncomment below to declare an instance variable for RezeptPruefResult
        //private RezeptPruefResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RezeptPruefResult
            //instance = new RezeptPruefResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RezeptPruefResult
        /// </summary>
        [Test]
        public void RezeptPruefResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" RezeptPruefResult
            //Assert.IsInstanceOf(typeof(RezeptPruefResult), instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Uid'
        /// </summary>
        [Test]
        public void UidTest()
        {
            // TODO unit test for the property 'Uid'
        }
        /// <summary>
        /// Test the property 'Statusinfo'
        /// </summary>
        [Test]
        public void StatusinfoTest()
        {
            // TODO unit test for the property 'Statusinfo'
        }

    }

}
