/*
 * Webservice ArzTI API
 *
 * Kommunikation des Webservers mit den jeweiligen Rechenzentren V.2021-05-20 
 *
 * The version of the OpenAPI document: V1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ArzTiClient.Api;
using ArzTiClient.Model;
using ArzTiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ArzTiClient.Test
{
    /// <summary>
    ///  Class for testing Rezept
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RezeptTests
    {
        // TODO uncomment below to declare an instance variable for Rezept
        //private Rezept instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Rezept
            //instance = new Rezept();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Rezept
        /// </summary>
        [Test]
        public void RezeptInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Rezept
            //Assert.IsInstanceOf(typeof(Rezept), instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Uid'
        /// </summary>
        [Test]
        public void UidTest()
        {
            // TODO unit test for the property 'Uid'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Apoik'
        /// </summary>
        [Test]
        public void ApoikTest()
        {
            // TODO unit test for the property 'Apoik'
        }

    }

}
