/*
 * Webservice ArzTI API
 *
 * Kommunikation des Webservers mit den jeweiligen Rechenzentren V.2021-05-20 
 *
 * The version of the OpenAPI document: V1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ArzTiClient.Api;
using ArzTiClient.Model;
using ArzTiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ArzTiClient.Test
{
    /// <summary>
    ///  Class for testing Statusinfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StatusinfoTests
    {
        // TODO uncomment below to declare an instance variable for Statusinfo
        //private Statusinfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Statusinfo
            //instance = new Statusinfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Statusinfo
        /// </summary>
        [Test]
        public void StatusinfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Statusinfo
            //Assert.IsInstanceOf(typeof(Statusinfo), instance);
        }


        /// <summary>
        /// Test the property 'Fcode'
        /// </summary>
        [Test]
        public void FcodeTest()
        {
            // TODO unit test for the property 'Fcode'
        }
        /// <summary>
        /// Test the property 'Fstatus'
        /// </summary>
        [Test]
        public void FstatusTest()
        {
            // TODO unit test for the property 'Fstatus'
        }
        /// <summary>
        /// Test the property 'Fkommentar'
        /// </summary>
        [Test]
        public void FkommentarTest()
        {
            // TODO unit test for the property 'Fkommentar'
        }
        /// <summary>
        /// Test the property 'Ftcode'
        /// </summary>
        [Test]
        public void FtcodeTest()
        {
            // TODO unit test for the property 'Ftcode'
        }
        /// <summary>
        /// Test the property 'Posnr'
        /// </summary>
        [Test]
        public void PosnrTest()
        {
            // TODO unit test for the property 'Posnr'
        }
        /// <summary>
        /// Test the property 'Fkurztext'
        /// </summary>
        [Test]
        public void FkurztextTest()
        {
            // TODO unit test for the property 'Fkurztext'
        }

    }

}
